// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Amqp is an autogenerated mock type for the Amqp type
type Amqp struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, exchangeName, routingKey, msg
func (_m *Amqp) Publish(ctx context.Context, exchangeName string, routingKey string, msg interface{}) error {
	ret := _m.Called(ctx, exchangeName, routingKey, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = rf(ctx, exchangeName, routingKey, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAmqp creates a new instance of Amqp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAmqp(t interface {
	mock.TestingT
	Cleanup(func())
}) *Amqp {
	mock := &Amqp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
