// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RateLimitStorage is an autogenerated mock type for the RateLimitStorage type
type RateLimitStorage struct {
	mock.Mock
}

// GetLastRequestTime provides a mock function with given fields: ctx, email
func (_m *RateLimitStorage) GetLastRequestTime(ctx context.Context, email string) (time.Time, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetLastRequestTime")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (time.Time, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) time.Time); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLastRequestTime provides a mock function with given fields: ctx, email, t
func (_m *RateLimitStorage) UpdateLastRequestTime(ctx context.Context, email string, t time.Time) error {
	ret := _m.Called(ctx, email, t)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastRequestTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, email, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRateLimitStorage creates a new instance of RateLimitStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateLimitStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateLimitStorage {
	mock := &RateLimitStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
