// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ARUMANDESU/uniclubs-user-service/internal/domain"
	dtos "github.com/ARUMANDESU/uniclubs-user-service/internal/domain/dtos"

	mock "github.com/stretchr/testify/mock"

	uniclubs_user_service_v1_userv1 "github.com/ARUMANDESU/uniclubs-protos/gen/go/user"
)

// Auth is an autogenerated mock type for the Auth type
type Auth struct {
	mock.Mock
}

type Auth_Expecter struct {
	mock *mock.Mock
}

func (_m *Auth) EXPECT() *Auth_Expecter {
	return &Auth_Expecter{mock: &_m.Mock}
}

// ActivateUser provides a mock function with given fields: ctx, token
func (_m *Auth) ActivateUser(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ActivateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Auth_ActivateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateUser'
type Auth_ActivateUser_Call struct {
	*mock.Call
}

// ActivateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Auth_Expecter) ActivateUser(ctx interface{}, token interface{}) *Auth_ActivateUser_Call {
	return &Auth_ActivateUser_Call{Call: _e.mock.On("ActivateUser", ctx, token)}
}

func (_c *Auth_ActivateUser_Call) Run(run func(ctx context.Context, token string)) *Auth_ActivateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Auth_ActivateUser_Call) Return(_a0 error) *Auth_ActivateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Auth_ActivateUser_Call) RunAndReturn(run func(context.Context, string) error) *Auth_ActivateUser_Call {
	_c.Call.Return(run)
	return _c
}

// Authenticate provides a mock function with given fields: ctx, sessionToken
func (_m *Auth) Authenticate(ctx context.Context, sessionToken string) (int64, error) {
	ret := _m.Called(ctx, sessionToken)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, sessionToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, sessionToken)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Auth_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type Auth_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken string
func (_e *Auth_Expecter) Authenticate(ctx interface{}, sessionToken interface{}) *Auth_Authenticate_Call {
	return &Auth_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, sessionToken)}
}

func (_c *Auth_Authenticate_Call) Run(run func(ctx context.Context, sessionToken string)) *Auth_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Auth_Authenticate_Call) Return(userID int64, err error) *Auth_Authenticate_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *Auth_Authenticate_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *Auth_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// CheckUserRole provides a mock function with given fields: ctx, userId, roles
func (_m *Auth) CheckUserRole(ctx context.Context, userId int64, roles []uniclubs_user_service_v1_userv1.Role) (bool, error) {
	ret := _m.Called(ctx, userId, roles)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserRole")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []uniclubs_user_service_v1_userv1.Role) (bool, error)); ok {
		return rf(ctx, userId, roles)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []uniclubs_user_service_v1_userv1.Role) bool); ok {
		r0 = rf(ctx, userId, roles)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []uniclubs_user_service_v1_userv1.Role) error); ok {
		r1 = rf(ctx, userId, roles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Auth_CheckUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserRole'
type Auth_CheckUserRole_Call struct {
	*mock.Call
}

// CheckUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int64
//   - roles []uniclubs_user_service_v1_userv1.Role
func (_e *Auth_Expecter) CheckUserRole(ctx interface{}, userId interface{}, roles interface{}) *Auth_CheckUserRole_Call {
	return &Auth_CheckUserRole_Call{Call: _e.mock.On("CheckUserRole", ctx, userId, roles)}
}

func (_c *Auth_CheckUserRole_Call) Run(run func(ctx context.Context, userId int64, roles []uniclubs_user_service_v1_userv1.Role)) *Auth_CheckUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]uniclubs_user_service_v1_userv1.Role))
	})
	return _c
}

func (_c *Auth_CheckUserRole_Call) Return(_a0 bool, _a1 error) *Auth_CheckUserRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Auth_CheckUserRole_Call) RunAndReturn(run func(context.Context, int64, []uniclubs_user_service_v1_userv1.Role) (bool, error)) *Auth_CheckUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *Auth) Login(ctx context.Context, email string, password string) (*domain.User, string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Auth_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Auth_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *Auth_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *Auth_Login_Call {
	return &Auth_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *Auth_Login_Call) Run(run func(ctx context.Context, email string, password string)) *Auth_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Auth_Login_Call) Return(_a0 *domain.User, token string, err error) *Auth_Login_Call {
	_c.Call.Return(_a0, token, err)
	return _c
}

func (_c *Auth_Login_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, string, error)) *Auth_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, sessionToken
func (_m *Auth) Logout(ctx context.Context, sessionToken string) error {
	ret := _m.Called(ctx, sessionToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Auth_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type Auth_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionToken string
func (_e *Auth_Expecter) Logout(ctx interface{}, sessionToken interface{}) *Auth_Logout_Call {
	return &Auth_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionToken)}
}

func (_c *Auth_Logout_Call) Run(run func(ctx context.Context, sessionToken string)) *Auth_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Auth_Logout_Call) Return(_a0 error) *Auth_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Auth_Logout_Call) RunAndReturn(run func(context.Context, string) error) *Auth_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, _a1
func (_m *Auth) Register(ctx context.Context, _a1 *dtos.UserRegisterDTO) (int64, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.UserRegisterDTO) (int64, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.UserRegisterDTO) int64); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dtos.UserRegisterDTO) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Auth_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Auth_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *dtos.UserRegisterDTO
func (_e *Auth_Expecter) Register(ctx interface{}, _a1 interface{}) *Auth_Register_Call {
	return &Auth_Register_Call{Call: _e.mock.On("Register", ctx, _a1)}
}

func (_c *Auth_Register_Call) Run(run func(ctx context.Context, _a1 *dtos.UserRegisterDTO)) *Auth_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dtos.UserRegisterDTO))
	})
	return _c
}

func (_c *Auth_Register_Call) Return(userID int64, err error) *Auth_Register_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *Auth_Register_Call) RunAndReturn(run func(context.Context, *dtos.UserRegisterDTO) (int64, error)) *Auth_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuth creates a new instance of Auth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *Auth {
	mock := &Auth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
