// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/ARUMANDESU/uniclubs-user-service/internal/domain/dtos"
	mock "github.com/stretchr/testify/mock"

	uniclubs_user_service_v1_userv1 "github.com/ARUMANDESU/uniclubs-protos/gen/go/user"
)

// Auth is an autogenerated mock type for the Auth type
type Auth struct {
	mock.Mock
}

// ActivateUser provides a mock function with given fields: ctx, token
func (_m *Auth) ActivateUser(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ActivateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckUserRole provides a mock function with given fields: ctx, userId, roles
func (_m *Auth) CheckUserRole(ctx context.Context, userId int64, roles []uniclubs_user_service_v1_userv1.Role) (bool, error) {
	ret := _m.Called(ctx, userId, roles)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserRole")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []uniclubs_user_service_v1_userv1.Role) (bool, error)); ok {
		return rf(ctx, userId, roles)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []uniclubs_user_service_v1_userv1.Role) bool); ok {
		r0 = rf(ctx, userId, roles)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []uniclubs_user_service_v1_userv1.Role) error); ok {
		r1 = rf(ctx, userId, roles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *Auth) Login(ctx context.Context, email string, password string) (dtos.UserCredentialsDTO, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 dtos.UserCredentialsDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (dtos.UserCredentialsDTO, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) dtos.UserCredentialsDTO); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(dtos.UserCredentialsDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *Auth) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshToken provides a mock function with given fields: ctx, rtToken, jwtToken
func (_m *Auth) RefreshToken(ctx context.Context, rtToken string, jwtToken string) (dtos.UserCredentialsDTO, error) {
	ret := _m.Called(ctx, rtToken, jwtToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 dtos.UserCredentialsDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (dtos.UserCredentialsDTO, error)); ok {
		return rf(ctx, rtToken, jwtToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) dtos.UserCredentialsDTO); ok {
		r0 = rf(ctx, rtToken, jwtToken)
	} else {
		r0 = ret.Get(0).(dtos.UserCredentialsDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, rtToken, jwtToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, _a1
func (_m *Auth) Register(ctx context.Context, _a1 *dtos.UserRegisterDTO) (int64, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.UserRegisterDTO) (int64, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.UserRegisterDTO) int64); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dtos.UserRegisterDTO) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuth creates a new instance of Auth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *Auth {
	mock := &Auth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
