// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ARUMANDESU/uniclubs-user-service/internal/domain"
	dtos "github.com/ARUMANDESU/uniclubs-user-service/internal/domain/dtos"

	mock "github.com/stretchr/testify/mock"
)

// Management is an autogenerated mock type for the Management type
type Management struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: ctx, dto
func (_m *Management) ChangePassword(ctx context.Context, dto dtos.ChangeUserPasswordDTO) error {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.ChangeUserPasswordDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeUserRole provides a mock function with given fields: ctx, dto
func (_m *Management) ChangeUserRole(ctx context.Context, dto *dtos.ChangeRoleDTO) error {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for ChangeUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.ChangeRoleDTO) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *Management) DeleteUser(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ForgotPassword provides a mock function with given fields: ctx, email, barcode
func (_m *Management) ForgotPassword(ctx context.Context, email string, barcode string) error {
	ret := _m.Called(ctx, email, barcode)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, barcode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *Management) GetUser(ctx context.Context, userID int64) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchUsers provides a mock function with given fields: ctx, query, filters
func (_m *Management) SearchUsers(ctx context.Context, query string, filters domain.Filters) ([]*domain.User, domain.Metadata, error) {
	ret := _m.Called(ctx, query, filters)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []*domain.User
	var r1 domain.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Filters) ([]*domain.User, domain.Metadata, error)); ok {
		return rf(ctx, query, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Filters) []*domain.User); ok {
		r0 = rf(ctx, query, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.Filters) domain.Metadata); ok {
		r1 = rf(ctx, query, filters)
	} else {
		r1 = ret.Get(1).(domain.Metadata)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, domain.Filters) error); ok {
		r2 = rf(ctx, query, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateAvatar provides a mock function with given fields: ctx, userID, imageUrl
func (_m *Management) UpdateAvatar(ctx context.Context, userID int64, imageUrl string) (*domain.User, string, error) {
	ret := _m.Called(ctx, userID, imageUrl)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAvatar")
	}

	var r0 *domain.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*domain.User, string, error)); ok {
		return rf(ctx, userID, imageUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *domain.User); ok {
		r0 = rf(ctx, userID, imageUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) string); ok {
		r1 = rf(ctx, userID, imageUrl)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, string) error); ok {
		r2 = rf(ctx, userID, imageUrl)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateUser provides a mock function with given fields: ctx, dto
func (_m *Management) UpdateUser(ctx context.Context, dto dtos.UpdateUserDTO) (domain.User, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.UpdateUserDTO) (domain.User, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.UpdateUserDTO) domain.User); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.UpdateUserDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewManagement creates a new instance of Management. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManagement(t interface {
	mock.TestingT
	Cleanup(func())
}) *Management {
	mock := &Management{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
